config/routes.rb
Rails.application.routes.draw do
  get 'choice/show'
  get 'question/show'
  get 'question/update'

  scope controller: 'choice' do
    get 'choice/:question_id' => :new, as: :choice_new
    post 'choice/create' => :create, as: :choice_create
    get 'choice/:question_id/all' => :index, as: :choice_index
    delete 'choice/:id' => :delete, as: :choice_delete
    get 'choice/:id/edit' => :edit , as: :choice_edit
    patch 'choice/:id/update' => :update, as: :choice_update
  end

  scope controller: 'test_takers' do
    get "users/:test_id" => :index, as: :test_takers_index
    get "users/:test_id/new" => :new, as: :test_takers_new
    post "users/:test_id/create" => :create, as: :test_takers_create
  end

  scope controller: 'static' do
    get 'not_found' => :not_found
    get 'error' => :error
  end

  scope controller: 'question' do
    get ':test/question/new' => :new, as: :question_new
    post ':test/question/create' => :create, as: :question_create
    delete 'question/:id' => :delete, as: :question_delete
  end

  get 'admin/index'
  get 'admin/tests'
  get 'admin/new_test'
  get 'sessions/destroy'

  scope controller: 'admin' do
    get 'deploy/:id' => :deploy, as: :admin_test_deploy
    patch 'deploy/:id' => :deploy, as: :admin_test_deploy_edit
  end

  scope controller: 'sessions' do
    get 'login' => :new
    post 'login' => :create, as: :login_session
    delete 'logout' => :destroy
  end

  scope controller: 'tests' do
    get 'tests/new' => :new
    post 'tests/create' => :create
    get 'tests/:id' => :show, as: "tests_show"
  end

  resources :users
  resources :events

  # Assignment controller routes.
  scope controller: 'assignments' do
    get '/assignments', action: 'index', as: 'assignments_index'
    get '/assignment/:id', action: 'show', as: 'assignments_show'
  end

  scope controller: 'student_assignments' do
    get '/feed/:id', action: 'feed', as: 'student_assignments_view_events'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  validates :name, uniqueness: true
  has_many :student_assignments
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
end

app/models/event.rb
class Event < ApplicationRecord
  enum event_type: { click: 0, click_and_drag: 1, clipboard: 2, tab_switch: 3, start: 4, copy: 5, paste: 6 }
  belongs_to :student_assignment

  # Determine event type from string
  def self.type_from(event_type)
    case event_type
    when "click"
      0
    when "click-and-drag"
      1
    when "clipboard"
      2
    when "tab-switch"
      3
    when "start"
      4
    when "copy"
      5
    when "paste"
      6
    else
      raise RuntimeError.new("FUCK")
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :choices, dependent: :destroy

  validates :test, presence: true

  def type
    choices = self.choices.where(correct: true).length
    case
    when choices == 0
      :incomplete
    when choices == 1
      :multiple_choice
    else
      :select_all_that_apply
    end
  end

end

app/models/student.rb
class Student < ApplicationRecord
  has_many :student_assignments
end

app/models/student_assignment.rb
class StudentAssignment < ApplicationRecord
  belongs_to :student
  belongs_to :assignment

  # The event stream for a given assignment student pair lives here.
  has_many :events

  EVENT_WEIGHTS = {
    click_and_drag: 5,
    visibility: 3,
    clipboard: 3,
    copy: 5,
    paste: 5,
    click: 0
  }

  # Creates a new event linked to the student assignment. Will parse the type.
  def new_event(event_type)
    events.create(event_type: Event.type_from(event_type))
  end

  # Calculate the cheat score for this student assignment
  def cheat_score
    raw = events.map{ |e| EVENT_WEIGHTS[e.event_type.to_sym] }.sum
    [raw, 100].min
  end
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :user
  has_many :questions
  has_many :test_memberships
  has_many :test_takers, through: :test_memberships

  validate :user_should_be_admin

  private

  def user_should_be_admin
    unless user.is_admin?
      errors.add(:user, "user must be admin")
    end
  end
end

app/models/test_membership.rb
class TestMembership < ApplicationRecord
  belongs_to :test_taker
  belongs_to :test
end

app/models/test_taker.rb
class TestTaker < ApplicationRecord
  has_many :test_memberships, dependent: :delete_all
  has_many :tests, through: :test_memberships
  validates_uniqueness_of :email
  before_destroy :delete_test_memberships

  def delete_test_memberships
    self.test_memberships.destroy_all
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  enum permissions: { user: 0, admin: 1, super_admin: 2 }
  has_secure_password

  def is_admin?
    User.permissions[permissions] > User.permissions["user"]
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def button_style
    "rounded-md bg-white px-3.5 py-2.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 mt-10"
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
  # Get the color class for a student's cheat score
  def cheat_color(student_assignment)
    unless student_assignment.cheat_score == 0
      'bg-red-300'
    end
  end
end

app/helpers/choice_helper.rb
module ChoiceHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/deploy.html.erb
<div>
    <h1>Deploy <%= @test.name %></h1>
    <p>Deployed: <%= @test.active %></p>

    <%= turbo_frame_tag "new_test_taker", src: test_takers_new_path(@test) do %>
    <% end %>

    <%= turbo_frame_tag "#{dom_id(@test)}_test_takers", src: test_takers_index_path(@test) do %>
    <% end %>

    <%= form_with model: @test, url: admin_test_deploy_edit_path(@test) do |f| %>
        <%= f.label :active, "Active:" %>
        <%= f.check_box :active %>

        <%= f.submit "Change deploy status" %>
    <% end %>
</div>

app/views/admin/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin#index</h1>
  <p>Find me in app/views/admin/index.html.erb</p>
</div>

app/views/admin/new_test.html.erb
<%= form_for(@test) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :description %>
    <%= f.text_field :description %>
<% end %%>

app/views/admin/tests.html.erb
<div>
    <%= link_to "New Test", tests_new_path, class: "text-indigo-600 hover:text-indigo-900" %>
    <table class="table-auto pt-5">
        <thead>
            <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Active?</th>
            <th>Registered Users</th>
            <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @tests.each do |test| %>
                <tr>
                    <td><%= link_to test.name, tests_show_path(test), class: "text-indigo-600 hover:text-indigo-900" %></td>
                    <td><%= test.description %></td>
                    <td><%= test.active %></td>
                    <td><%= test.test_takers.count %></td>
                    <td>
                        <%= link_to "Deploy", admin_test_deploy_path(test) %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/layouts/admin_layout.html.erb
<html class="h-full bg-white">
  <head>
    <title>SniffAiBackend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-full">
  <div>
    <div class="lg:pl-72">
      <nav class="menu">
        <%= link_to "Test Management", admin_tests_path %>
      </nav>
      <main class="py-10">
        <div class="px-4 sm:px-6 lg:px-8">
          <%= yield %>
        </div>
      </main>
    </div>
  </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SniffAiBackend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>