config/routes.rb
Rails.application.routes.draw do
  get 'choice/show'
  get 'question/show'
  get 'question/update'

  scope controller: 'choice' do
    get 'choice/:question_id' => :new, as: :choice_new
    post 'choice/create' => :create, as: :choice_create
    get 'choice/:question_id/all' => :index, as: :choice_index
    delete 'choice/:id' => :delete, as: :choice_delete
    get 'choice/:id/edit' => :edit , as: :choice_edit
    patch 'choice/:id/update' => :update, as: :choice_update
  end

  scope controller: 'test_takers' do
    get "users/:test_id" => :index, as: :test_takers_index
    get "users/:test_id/new" => :new, as: :test_takers_new
    post "users/:test_id/create" => :create, as: :test_takers_create
  end

  scope controller: 'static' do
    get 'not_found' => :not_found
    get 'error' => :error
  end

  scope controller: 'question' do
    get ':test/question/new' => :new, as: :question_new
    post ':test/question/create' => :create, as: :question_create
    delete 'question/:id' => :delete, as: :question_delete
  end

  get 'admin/index'
  get 'admin/tests'
  get 'admin/new_test'
  get 'sessions/destroy'

  scope controller: 'admin' do
    get 'deploy/:id' => :deploy, as: :admin_test_deploy
    patch 'deploy/:id' => :deploy, as: :admin_test_deploy_edit
  end

  scope controller: 'sessions' do
    get 'login' => :new
    post 'login' => :create, as: :login_session
    delete 'logout' => :destroy
  end

  scope controller: 'tests' do
    get 'tests/new' => :new
    post 'tests/create' => :create
    get 'tests/:id' => :show, as: "tests_show"
  end

  resources :users
  resources :events

  # Assignment controller routes.
  scope controller: 'assignments' do
    get '/assignments', action: 'index', as: 'assignments_index'
    get '/assignment/:id', action: 'show', as: 'assignments_show'
  end

  scope controller: 'student_assignments' do
    get '/feed/:id', action: 'feed', as: 'student_assignments_view_events'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  validates :name, uniqueness: true
  has_many :student_assignments
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
end

app/models/event.rb
class Event < ApplicationRecord
  enum event_type: { click: 0, click_and_drag: 1, clipboard: 2, tab_switch: 3, start: 4, copy: 5, paste: 6 }
  belongs_to :student_assignment

  # Determine event type from string
  def self.type_from(event_type)
    case event_type
    when "click"
      0
    when "click-and-drag"
      1
    when "clipboard"
      2
    when "tab-switch"
      3
    when "start"
      4
    when "copy"
      5
    when "paste"
      6
    else
      raise RuntimeError.new("FUCK")
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :choices, dependent: :destroy

  validates :test, presence: true

  def type
    choices = self.choices.where(correct: true).length
    case
    when choices == 0
      :incomplete
    when choices == 1
      :multiple_choice
    else
      :select_all_that_apply
    end
  end

end

app/models/student.rb
class Student < ApplicationRecord
  has_many :student_assignments
end

app/models/student_assignment.rb
class StudentAssignment < ApplicationRecord
  belongs_to :student
  belongs_to :assignment

  # The event stream for a given assignment student pair lives here.
  has_many :events

  EVENT_WEIGHTS = {
    click_and_drag: 5,
    visibility: 3,
    clipboard: 3,
    copy: 5,
    paste: 5,
    click: 0
  }

  # Creates a new event linked to the student assignment. Will parse the type.
  def new_event(event_type)
    events.create(event_type: Event.type_from(event_type))
  end

  # Calculate the cheat score for this student assignment
  def cheat_score
    raw = events.map{ |e| EVENT_WEIGHTS[e.event_type.to_sym] }.sum
    [raw, 100].min
  end
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :user
  has_many :questions
  has_many :test_memberships
  has_many :test_takers, through: :test_memberships

  validate :user_should_be_admin

  private

  def user_should_be_admin
    unless user.is_admin?
      errors.add(:user, "user must be admin")
    end
  end
end

app/models/test_membership.rb
class TestMembership < ApplicationRecord
  belongs_to :test_taker
  belongs_to :test
end

app/models/test_taker.rb
class TestTaker < ApplicationRecord
  has_many :test_memberships, dependent: :delete_all
  has_many :tests, through: :test_memberships
  validates_uniqueness_of :email
  before_destroy :delete_test_memberships

  def delete_test_memberships
    self.test_memberships.destroy_all
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  enum permissions: { user: 0, admin: 1, super_admin: 2 }
  has_secure_password

  def is_admin?
    User.permissions[permissions] > User.permissions["user"]
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  # Specify using our admin layout specifically
  layout "admin_layout"

  before_action :require_login
  before_action :check_user_scope
  before_action :set_test, only: %i[deploy]

  def index
  end

  ##
  # Manage tests
  #
  def tests
    @tests = Test.all
  end

  def deploy
    if request.patch?
      @test.active = test_params[:active]
      @test.save
      return redirect_to admin_tests_url
    end
  end

  private
  def set_test
    @test = Test.find(params[:id])
  end

  def test_params
    params.require(:test).permit(:active)
  end
end

app/controllers/question_controller.rb
class QuestionController < ApplicationController
  layout "admin_layout"
  before_action :require_login
  before_action :check_user_scope
  before_action :set_question, only: %i[delete show]
  before_action :check_test_permissions, only: %i[delete]

  def new
    @question = Question.new(test_id: params[:test_id])

    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  def create
    @question = Question.new(test_id: params[:test].to_i, **question_params)
    if @question.save
      respond_to do |format|
        format.turbo_stream
        format.html
      end
    else
    end
  end

  def show
  end

  def update
  end

  def delete
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:text)
  end

  # The question should be in the test and the user that created the test should be the requester.
  def check_test_permissions
    test = Test.find(@question.test_id)
    test&.user == @user
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def button_style
    "rounded-md bg-white px-3.5 py-2.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 mt-10"
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
  # Get the color class for a student's cheat score
  def cheat_color(student_assignment)
    unless student_assignment.cheat_score == 0
      'bg-red-300'
    end
  end
end

app/helpers/choice_helper.rb
module ChoiceHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/test_takers_helper.rb
module TestTakersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/question/_form.html.erb
<%= form_with model: @question, url: question_create_path do |form| %>
  <%= form.label :text, "Enter question text" %>
  <%= form.text_area :text, size: "60x10" %>

  <%= form.submit "Add question", class: "bg-slate-400 p-4 rounded-sm shadow-md cursor-pointer" %>
<% end %>

app/views/question/_question.html.erb
<%= turbo_frame_tag dom_id(question) do %>
    <li>
        <div>
            <h1><%= question.text %></h1>
            <%= link_to "Delete question", question_delete_path(question),
                data: { turbo_method: :delete }%>

            <%= turbo_frame_tag "#{dom_id(question)}_choices", src: choice_index_path(question) do %>
            <% end %>

            <%# Add a new choice form populates initially %>
            <%= turbo_frame_tag "#{dom_id(question)}_add_choice" do %>
                <% if question.choices.blank? %>
                    <%= render partial: "choice/form", locals: { question: question, choice: Choice.new } %>
                <% else %>
                    <%= link_to "Add Choice", choice_new_path(question), data: { turbo_stream: true } %>
                <% end %>
            <% end %>
        </div>
    </li>
<% end %>

app/views/question/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Question#create</h1>
  <p>Find me in app/views/question/create.html.erb</p>
</div>

app/views/question/create.turbo_stream.erb
<%= turbo_stream.append "questions" do %>
    <%= render partial: 'question/question', object: @question %>
<% end %>

<%= turbo_stream.replace "new_question" do %>
<% end %>

app/views/question/delete.html.erb
<div>
  <h1 class="font-bold text-4xl">Question#delete</h1>
  <p>Find me in app/views/question/delete.html.erb</p>
</div>

app/views/question/delete.turbo_stream.erb
<%= turbo_stream.remove dom_id(@question) do %>
<% end %>

app/views/question/new.html.erb
<div>
  <h1 class="font-bold text-4xl">Question#new</h1>
  <p>Find me in app/views/question/new.html.erb</p>

  <%= render "form", locals: { question: @question } %>
</div>

app/views/question/new.turbo_stream.erb
<%= turbo_stream.update "new_question" do %>
    <%= render partial: "form", locals: { question: @question } %>
<% end %>

app/views/question/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Question#show</h1>
  <p>Find me in app/views/question/show.html.erb</p>
</div>

app/views/question/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Question#update</h1>
  <p>Find me in app/views/question/update.html.erb</p>
</div>