config/routes.rb
Rails.application.routes.draw do
  get 'choice/show'
  get 'question/show'
  get 'question/update'

  scope controller: 'choice' do
    get 'choice/:question_id' => :new, as: :choice_new
    post 'choice/create' => :create, as: :choice_create
    get 'choice/:question_id/all' => :index, as: :choice_index
    delete 'choice/:id' => :delete, as: :choice_delete
    get 'choice/:id/edit' => :edit , as: :choice_edit
    patch 'choice/:id/update' => :update, as: :choice_update
  end

  scope controller: 'test_takers' do
    get "users/:test_id" => :index, as: :test_takers_index
    get "users/:test_id/new" => :new, as: :test_takers_new
    post "users/:test_id/create" => :create, as: :test_takers_create
  end

  scope controller: 'static' do
    get 'not_found' => :not_found
    get 'error' => :error
  end

  scope controller: 'question' do
    get ':test/question/new' => :new, as: :question_new
    post ':test/question/create' => :create, as: :question_create
    delete 'question/:id' => :delete, as: :question_delete
  end

  get 'admin/index'
  get 'admin/tests'
  get 'admin/new_test'
  get 'sessions/destroy'

  scope controller: 'admin' do
    get 'deploy/:id' => :deploy, as: :admin_test_deploy
    patch 'deploy/:id' => :deploy, as: :admin_test_deploy_edit
  end

  scope controller: 'sessions' do
    get 'login' => :new
    post 'login' => :create, as: :login_session
    delete 'logout' => :destroy
  end

  scope controller: 'tests' do
    get 'tests/new' => :new
    post 'tests/create' => :create
    get 'tests/:id' => :show, as: "tests_show"
  end

  resources :users
  resources :events

  # Assignment controller routes.
  scope controller: 'assignments' do
    get '/assignments', action: 'index', as: 'assignments_index'
    get '/assignment/:id', action: 'show', as: 'assignments_show'
  end

  scope controller: 'student_assignments' do
    get '/feed/:id', action: 'feed', as: 'student_assignments_view_events'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  validates :name, uniqueness: true
  has_many :student_assignments
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
end

app/models/event.rb
class Event < ApplicationRecord
  enum event_type: { click: 0, click_and_drag: 1, clipboard: 2, tab_switch: 3, start: 4, copy: 5, paste: 6 }
  belongs_to :student_assignment

  # Determine event type from string
  def self.type_from(event_type)
    case event_type
    when "click"
      0
    when "click-and-drag"
      1
    when "clipboard"
      2
    when "tab-switch"
      3
    when "start"
      4
    when "copy"
      5
    when "paste"
      6
    else
      raise RuntimeError.new("FUCK")
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :choices, dependent: :destroy

  validates :test, presence: true

  def type
    choices = self.choices.where(correct: true).length
    case
    when choices == 0
      :incomplete
    when choices == 1
      :multiple_choice
    else
      :select_all_that_apply
    end
  end

end

app/models/student.rb
class Student < ApplicationRecord
  has_many :student_assignments
end

app/models/student_assignment.rb
class StudentAssignment < ApplicationRecord
  belongs_to :student
  belongs_to :assignment

  # The event stream for a given assignment student pair lives here.
  has_many :events

  EVENT_WEIGHTS = {
    click_and_drag: 5,
    visibility: 3,
    clipboard: 3,
    copy: 5,
    paste: 5,
    click: 0
  }

  # Creates a new event linked to the student assignment. Will parse the type.
  def new_event(event_type)
    events.create(event_type: Event.type_from(event_type))
  end

  # Calculate the cheat score for this student assignment
  def cheat_score
    raw = events.map{ |e| EVENT_WEIGHTS[e.event_type.to_sym] }.sum
    [raw, 100].min
  end
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :user
  has_many :questions
  has_many :test_memberships
  has_many :test_takers, through: :test_memberships

  validate :user_should_be_admin

  private

  def user_should_be_admin
    unless user.is_admin?
      errors.add(:user, "user must be admin")
    end
  end
end

app/models/test_membership.rb
class TestMembership < ApplicationRecord
  belongs_to :test_taker
  belongs_to :test
end

app/models/test_taker.rb
class TestTaker < ApplicationRecord
  has_many :test_memberships, dependent: :delete_all
  has_many :tests, through: :test_memberships
  validates_uniqueness_of :email
  before_destroy :delete_test_memberships

  def delete_test_memberships
    self.test_memberships.destroy_all
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  enum permissions: { user: 0, admin: 1, super_admin: 2 }
  has_secure_password

  def is_admin?
    User.permissions[permissions] > User.permissions["user"]
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  # Specify using our admin layout specifically
  layout "admin_layout"

  before_action :require_login
  before_action :check_user_scope
  before_action :set_test, only: %i[deploy]

  def index
  end

  ##
  # Manage tests
  #
  def tests
    @tests = Test.all
  end

  def deploy
    if request.patch?
      @test.active = test_params[:active]
      @test.save
      return redirect_to admin_tests_url
    end
  end

  private
  def set_test
    @test = Test.find(params[:id])
  end

  def test_params
    params.require(:test).permit(:active)
  end
end

app/controllers/choice_controller.rb
class ChoiceController < ApplicationController
  before_action :require_login
  before_action :check_user_scope
  before_action :set_question, only: %i[index new create]

  def index
    @choices = Choice.where(question_id: params[:question_id])
    respond_to do |format|
      format.html
    end
  end

  def new
    @choice = Choice.new(question_id: params[:question_id])
    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  def create
    @choice = Choice.new(choice_params)
    if @choice.save
      respond_to do |format|
        format.turbo_stream
        format.html
      end
    else
      # TODO: Fill out errors.
    end
  end

  def show
  end

  def edit
    @choice = Choice.find(params[:id])
  end

  def update
    @choice = Choice.find(params[:id])
    @choice.update(**choice_params)
    @choice.save
    respond_to do |format|
      format.turbo_stream
    end
  end

  def delete
    @choice = Choice.find(params[:id])
    @choice.destroy
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_question
    question_id = params[:question_id].nil? ? choice_params[:question_id] : params[:question_id]
    @question = Question.find(question_id)
  end

  def choice_params
    params.require(:choice).permit(:value, :correct, :question_id)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def button_style
    "rounded-md bg-white px-3.5 py-2.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 mt-10"
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
  # Get the color class for a student's cheat score
  def cheat_color(student_assignment)
    unless student_assignment.cheat_score == 0
      'bg-red-300'
    end
  end
end

app/helpers/choice_helper.rb
module ChoiceHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/test_takers_helper.rb
module TestTakersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/choice/_choice.html.erb
<%= turbo_frame_tag dom_id(choice) do %>
    <div>
        <p>Correct: <%= choice.correct %></p>
        <p><%= choice.value %></p>
        Actions:
        <%= link_to "Delete Choice", choice_delete_path(choice), data: { turbo_method: :delete } %>
        <%= link_to "Edit Choice", choice_edit_path(choice), data: { turbo_stream: true } %>
    </div>
<% end %>

app/views/choice/_form.html.erb
<%= form_with model: choice, url: choice.id.blank? ? choice_create_path : choice_update_path(choice) do |f| %>
    <%= f.label :correct, "Correct Answer:" %>
    <%= f.check_box :correct %>

    <%= f.label :value, "Choice text:" %>
    <%= f.text_field :value %>
    <%= f.hidden_field :question_id, value: choice.question_id.blank? ? question.id : choice.question_id %>
    <%= f.submit "Add choice" %>
<% end %>

app/views/choice/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Choice#create</h1>
  <p>Find me in app/views/choice/create.html.erb</p>
</div>

app/views/choice/create.turbo_stream.erb
<%= turbo_stream.append "#{dom_id(@question)}_choices" do %>
    <%= render partial: 'choice', locals: { choice: @choice } %>
<% end %>

<%= turbo_stream.update "#{dom_id(@question)}_add_choice" do %>
    <%= link_to "Add choice", choice_new_path(@question), data: { turbo_stream: true } %>
<% end %>

app/views/choice/delete.html.erb
<div>
  <h1 class="font-bold text-4xl">Choice#delete</h1>
  <p>Find me in app/views/choice/delete.html.erb</p>
</div>

app/views/choice/delete.turbo_stream.erb
<%= turbo_stream.remove dom_id(@choice) %>

app/views/choice/edit.turbo_stream.erb
<%= turbo_stream.replace dom_id(@choice) do %>
    <%= turbo_frame_tag dom_id(@choice) do %>
        <%= render partial: 'form', locals: { choice: @choice } %>
    <% end %>
<% end %>

app/views/choice/index.html.erb
<%= turbo_frame_tag "#{dom_id(@question)}_choices" do %>
    <% render partial: 'choice', collection: @choices %>
<% end %>

app/views/choice/index.turbo_stream.erb
<%= turbo_stream.replace "#{dom_id(@question)}_choices" %>
    <% render partial: 'choice', collection: @choices %>
<% end %>

app/views/choice/new.html.erb
<h1>Choice Form</h1>

app/views/choice/new.turbo_stream.erb
<%= turbo_stream.update "#{dom_id(@question)}_add_choice" do %>
    <%= render partial: 'form', locals: { choice: @choice } %>
<% end %>

app/views/choice/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Choice#show</h1>
  <p>Find me in app/views/choice/show.html.erb</p>
</div>

app/views/choice/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Choice#update</h1>
  <p>Find me in app/views/choice/update.html.erb</p>
</div>

app/views/choice/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@choice) do %>
    <%= render partial: 'choice', locals: { choice: @choice } %>
<% end %>